### ISSUE TITLE
有没有sql测试数据啊

### ISSUE THREAD

**Issue by rehack** [JerryLoveZhiXin/SimplePHP#1]
如题

**Comment by SmallOyster** [comment]
有滴哈，稍等上传哦！

**Comment by SmallOyster** [comment]
[初始导入SQL](https://github.com/SmallOyster/SimplePHP/blob/master/SimplePHP.sql)

如果导入过程中有错误，欢迎继续提问哦 :smiley:

> SmallOyster 小生蚝 半专业PHP码农

**Comment by rehack** [comment]
@SmallOyster  谢谢 ！我这几天被逼无奈 要捣鼓一个会员积分系统 ，愁死我了

**Comment by SmallOyster** [comment]
哦，积分的话可以直接在list表加字段，然后再在前台搞个积分页面就好啦！

其实数据库库名和表名都可以改的啦~

我只是举例子而已！

多嘴问一句：您会PHP吧？

**Comment by rehack** [comment]
我只是个小前端，我们这没有做后端的，所以。。。

**Comment by SmallOyster** [comment]
@codesboy 哦。
